version: '3'
networks:
  iais-network:

services:
  iais-postgres:
    networks:
      - iais-network
    image: parstat.azurecr.io/iais-postgres:latest
    ports:
    - "5432:5432"
    hostname: iais-postgres

  iais-zuul:
    networks:
      - iais-network
    image: parstat.azurecr.io/iais-zuul:latest
    ports:
      - "8080:8080"
    hostname: iais-zuul
    logging:
      driver: "json-file"
      options:
        max-size: "300K"
        max-file: "1"

  iais-referential-api:
    networks:
      - iais-network
    image: parstat.azurecr.io/iais-referential-api
    hostname: iais-referential-api
    logging:
      driver: "json-file"
      options:
        max-size: "300K"
        max-file: "1"
    restart: always

  iais-ms-security-api:
    networks:
      - iais-network
    image: parstat.azurecr.io/iais-ms-security-api
    hostname: iais-ms-security-api
    logging:
      driver: "json-file"
      options:
        max-size: "300K"
        max-file: "1"
    restart: always

  iais-frontend:
    image: parstat.azurecr.io/iais-frontend
    hostname: iais-frontend
    ports:
      - "80:8090"
    logging:
      driver: "json-file"
      options:
        max-size: "300K"
        max-file: "1"
    restart: always


