package com.nbs.iais.ms.common.enums;

public enum EntityType {

    STATISTICAL_PROGRAM,
    BUSINESS_FUNCTION,
    PROCESS_DOCUMENTATION,
    AGENT,
    ROLE,
    PROCESS_METHOD,
    PROCESS_QUALITY,
    STATISTICAL_STANDARD_REFERENCE,
    LEGISLATIVE_REFERENCE,
    BUSINESS_SERVICE,
    PROCESS_INPUT_SPECIFICATION,
    PROCESS_OUTPUT_SPECIFICATION,
    PROCESS_DOCUMENT
}
