package com.nbs.iais.ms.common.enums;

public enum ExceptionCodes {
    SYSTEM_ERROR, PASSWORD_NO_MACH, USERNAME_OR_PASSWORD_WRONG, EMAIL_TAKEN, USERNAME_TAKEN, USER_LOCKED, USER_DELETED, NOT_FOUND
}
